---
title: Millennial
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
paginate: 5
markdown: kramdown
highlighter: rouge
permalink: "/:title"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
description: a minimalist Jekyll theme for running a blog or publication
author: Paul Le
