---
title: TrackOne Band
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
paginate: 5
markdown: kramdown
highlighter: rouge
permalink: "/:title"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
description: Rock covers in Central CT
author: guys@trackone.band
