basic_settings:
  site_title: 'TrackOne Band'
  site_tagline: 'Mainstream and alternative rock for Central Connecticut.'
  favicon_image: "/favicon.ico"
  default_social_image: "/images/drum-head-ogp-1200-630.png"
  site_url: 'https://trackone.band/'
  copyright_holder: "Adam Rich<a href='mailto:adam@trackone.band'>&lt;adam@trackone.band&gt;</a>"

header_settings:
  logo_image: "/images/trackone-handwritten-alpha-white.png"
  logo_width: 200  # CSS updated to show max-width of 80%.  See _header.scss
  overlay_opacity: 0.7
  default_header_image: "/images/drum-head-bw-ar67.png"

banner_settings:
  message: "Next show February 3!"
  url: "/2023/12/30/return-to-t3.html"
  # url: /gigs


menu_settings:
  menu_items:
    - title: 'News'
      url: '/'
    - title: 'Gigs'
      url: '/gigs'
    - title: 'Songs'
      url: '/songs'
    - title: 'About'
      url: '/about'
    - title: 'Contact'
      url: '/contact'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/f/xbjvynjw'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/trackone.band.ct'
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/trackone.band'
  snapchat_url: ''
  youtube_url: 'https://www.youtube.com/@trackone-band'
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  # soundcloud_url: 'https://soundcloud.com/trackone-band'
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''
  # threads_url: 'https://www.threads.net/@trackone.band'
  dropbox_url: 'https://www.dropbox.com/request/nNIUrCfBoWA1VWCgLK7Y'

color_settings:
  background_color: '#111111'
  background_alt_color: '#333333'

  text_dark_color: '#bbbbbb'
  text_medium_color: '#dddddd'
  text_light_color: '#ffffff'

  accent_color: '#B4ADEA'
  border_color: '#222222'
  error_color: '#A846A0'

  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'

  text_banner_color: '#000000'
  banner_background_color: '#FFE900'



  # Defaults ----------------------------
  # background_color: '#ffffff'
  # background_alt_color: '#F5F7FA'
  # text_dark_color: '#2A2F36'
  # text_medium_color: '#6C7A89'
  # text_light_color: '#ABB7B7'
  # accent_color: '#A2DED0'
  # border_color: '#dddddd'
  # overlay_background_color: '#161B21'
  # overlay_text_color: '#ffffff'
  # error_color: '#D64541


font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Muli:400,400i,600" rel="stylesheet">'
  title_font: '"Merriweather", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""

